rvm: 
  - 1.9.3
  - 1.9.2
  - 1.8.7
# whitelist
branches:
  only:
    - master
# Needed to build lexers
before_script: sudo apt-get install -y ragel=6.6-1

notifications:
  email:
    - cukes-devs@googlegroups.com